const data = [
  [
    {
      nameValue: "delete",
      nameLabel: "AC",
      background: "#BDBDBD",
      color: "#4F4F4F",
      flex_grow: 0,
    },
    {
      nameValue: "plus/minus",
      nameLabel: "+/-",
      background: "#BDBDBD",
      color: "#4F4F4F",
      flex_grow: 1,
    },
    {
      nameValue: "percent",
      nameLabel: "%",
      background: "#BDBDBD",
      color: "#4F4F4F",
      flex_grow: 2,
    },
    {
      nameValue: "divide",
      nameLabel: "÷",
      background: " #F0A143",
      color: "#F2F2F2",
      flex_grow: 3,
    },
  ],
  [
    {
      nameValue: "7",
      nameLabel: "7",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 0,
    },
    {
      nameValue: "8",
      nameLabel: "8",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 1,
    },
    {
      nameValue: "9",
      nameLabel: "9",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 2,
    },
    {
      nameValue: "multiply",
      nameLabel: "×",
      background: " #F0A143",
      color: "#F2F2F2",
      flex_grow: 3,
    },
  ],
  [
    {
      nameValue: "4",
      nameLabel: "4",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 0,
    },
    {
      nameValue: "5",
      nameLabel: "5",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 1,
    },
    {
      nameValue: "6",
      nameLabel: "6",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 2,
    },
    {
      nameValue: "minus",
      nameLabel: "-",
      background: " #F0A143",
      color: "#F2F2F2",
      flex_grow: 3,
    },
  ],
  [
    {
      nameValue: "1",
      nameLabel: "1",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 0,
    },
    {
      nameValue: "2",
      nameLabel: "2",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 1,
    },
    {
      nameValue: "3",
      nameLabel: "3",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 2,
    },
    {
      nameValue: "plus",
      nameLabel: "+",
      background: " #F0A143",
      color: "#F2F2F2",
      flex_grow: 3,
    },
  ],
  [
    {
      nameValue: "0",
      nameLabel: "0",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 2,
    },
    {
      nameValue: "dot",
      nameLabel: ".",
      background: "#828282",
      color: "#F2F2F2",
      flex_grow: 0,
    },
    {
      nameValue: "equal",
      nameLabel: "=",
      background: " #F0A143",
      color: "#F2F2F2",
      flex_grow: 0,
    },
  ],
];
